# Generated by Django 5.2.4 on 2025-07-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherApiQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("used", models.PositiveIntegerField(default=0)),
                ("limit", models.PositiveIntegerField(default=1000)),
            ],
            options={
                "verbose_name": "天气 API 月度配额",
                "unique_together": {("year", "month")},
            },
        ),
    ]
