# Generated by Django 5.2.4 on 2025-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="分类描述"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="标签描述"
            ),
        ),
    ]
